<a href="https://colab.research.google.com/github/hiromimi0705-cpu/pioneer_research/blob/main/Dataset_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I am interested in understanding what factors influence housing prices. Housing prices affect affordability and economic opportunities. This project will explore whether variables such as median income, population, and location can help predict housing values.

Dataset Name:
Japan Real Estate Prices

Source:
Kaggle

Link:
https://www.kaggle.com/datasets/nishiodens/japan-real-estate-transaction-prices?resource=download

Description:
This dataset is a record of real estate transaction prices in Japan from 2005 to 2019, surveyed by the MLIT(Ministry of Land, Infrastructure, Transport and Tourism of Japan).

In [4]:
from google.colab import files

uploaded = files.upload()

Saving 13.csv to 13.csv

In [7]:
import pandas as pd

df = pd.read_csv("13.csv")
df.head()

,No,Type,Region,MunicipalityCode,Prefecture,Municipality,DistrictName,NearestStation,TimeToNearestStation,MinTimeToNearestStation,...,Classification,Breadth,CityPlanning,CoverageRatio,FloorAreaRatio,Period,Year,Quarter,Renovation,Remarks
0,1,"Pre-owned Condominiums, etc.",NaN,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,4,4.0,...,NaN,NaN,Commercial Zone,80.0,500.0,3rd quarter 2019,2019,3,Not yet,NaN
1,2,"Pre-owned Condominiums, etc.",NaN,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,4,4.0,...,NaN,NaN,Commercial Zone,80.0,500.0,3rd quarter 2019,2019,3,Done,NaN
2,3,Residential Land(Land and Building),Commercial Area,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,2,2.0,...,Ward Road,4.0,Commercial Zone,80.0,500.0,2nd quarter 2019,2019,2,NaN,NaN
3,4,Residential Land(Land and Building),Commercial Area,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,1,1.0,...,Tokyo Metropolitan Road,27.0,Commercial Zone,80.0,700.0,2nd quarter 2019,2019,2,NaN,NaN
4,5,"Pre-owned Condominiums, etc.",NaN,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,4,4.0,...,NaN,NaN,Commercial Zone,80.0,500.0,2nd quarter 2019,2019,2,Done,NaN

In [8]:
df.shape

(406575, 38)

In [9]:
df.columns

Index(['No', 'Type', 'Region', 'MunicipalityCode', 'Prefecture',
       'Municipality', 'DistrictName', 'NearestStation',
       'TimeToNearestStation', 'MinTimeToNearestStation',
       'MaxTimeToNearestStation', 'TradePrice', 'FloorPlan', 'Area',
       'AreaIsGreaterFlag', 'UnitPrice', 'PricePerTsubo', 'LandShape',
       'Frontage', 'FrontageIsGreaterFlag', 'TotalFloorArea',
       'TotalFloorAreaIsGreaterFlag', 'BuildingYear', 'PrewarBuilding',
       'Structure', 'Use', 'Purpose', 'Direction', 'Classification', 'Breadth',
       'CityPlanning', 'CoverageRatio', 'FloorAreaRatio', 'Period', 'Year',
       'Quarter', 'Renovation', 'Remarks'],
      dtype='object')

In [10]:
df.dtypes

No                               int64
Type                            object
Region                          object
MunicipalityCode                 int64
Prefecture                      object
Municipality                    object
DistrictName                    object
NearestStation                  object
TimeToNearestStation            object
MinTimeToNearestStation        float64
MaxTimeToNearestStation        float64
TradePrice                       int64
FloorPlan                       object
Area                             int64
AreaIsGreaterFlag                int64
UnitPrice                      float64
PricePerTsubo                  float64
LandShape                       object
Frontage                       float64
FrontageIsGreaterFlag             bool
TotalFloorArea                 float64
TotalFloorAreaIsGreaterFlag      int64
BuildingYear                   float64
PrewarBuilding                   int64
Structure                       object
Use                             object
Purpose                         object
Direction                       object
Classification                  object
Breadth                        float64
CityPlanning                    object
CoverageRatio                  float64
FloorAreaRatio                 float64
Period                          object
Year                             int64
Quarter                          int64
Renovation                      object
Remarks                         object
dtype: object

In [11]:
df.isnull().sum()

No                                  0
Type                                0
Region                         184871
MunicipalityCode                    0
Prefecture                          0
Municipality                        0
DistrictName                      246
NearestStation                   1728
TimeToNearestStation            10339
MinTimeToNearestStation         10339
MaxTimeToNearestStation         10489
TradePrice                          0
FloorPlan                      228444
Area                                0
AreaIsGreaterFlag                   0
UnitPrice                      327072
PricePerTsubo                  327072
LandShape                      185273
Frontage                       203688
FrontageIsGreaterFlag               0
TotalFloorArea                 270150
TotalFloorAreaIsGreaterFlag         0
BuildingYear                    92279
PrewarBuilding                      0
Structure                       88218
Use                             97885
Purpose                        248844
Direction                      185295
Classification                 187742
Breadth                        188973
CityPlanning                     3826
CoverageRatio                    5915
FloorAreaRatio                   5915
Period                              0
Year                                0
Quarter                             0
Renovation                     240074
Remarks                        374809
dtype: int64

In [12]:
df.head()

,No,Type,Region,MunicipalityCode,Prefecture,Municipality,DistrictName,NearestStation,TimeToNearestStation,MinTimeToNearestStation,...,Classification,Breadth,CityPlanning,CoverageRatio,FloorAreaRatio,Period,Year,Quarter,Renovation,Remarks
0,1,"Pre-owned Condominiums, etc.",NaN,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,4,4.0,...,NaN,NaN,Commercial Zone,80.0,500.0,3rd quarter 2019,2019,3,Not yet,NaN
1,2,"Pre-owned Condominiums, etc.",NaN,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,4,4.0,...,NaN,NaN,Commercial Zone,80.0,500.0,3rd quarter 2019,2019,3,Done,NaN
2,3,Residential Land(Land and Building),Commercial Area,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,2,2.0,...,Ward Road,4.0,Commercial Zone,80.0,500.0,2nd quarter 2019,2019,2,NaN,NaN
3,4,Residential Land(Land and Building),Commercial Area,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,1,1.0,...,Tokyo Metropolitan Road,27.0,Commercial Zone,80.0,700.0,2nd quarter 2019,2019,2,NaN,NaN
4,5,"Pre-owned Condominiums, etc.",NaN,13101,Tokyo,Chiyoda Ward,Iidabashi,Iidabashi,4,4.0,...,NaN,NaN,Commercial Zone,80.0,500.0,2nd quarter 2019,2019,2,Done,NaN

AI Use Reference


I used ChatGPT to help me understand the assignment requirements, learn how to upload and load a dataset in Google Colab, understand how to create and use a GitHub repository, and generate example Python code for exploring the dataset. I reviewed and modified the notebook contents myself.